// <auto-generated />
using System;
using Intranet2.Datenbank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intranet2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260821065937_Umfragen")]
    partial class Umfragen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Intranet2.Datenbank.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("WindowsBenutzername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("WindowsBenutzername")
                        .IsUnique();

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.NewsBeitrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BildPfad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IstKurzmeldung")
                        .HasColumnType("bit");

                    b.Property<bool>("IstVeroeffentlicht")
                        .HasColumnType("bit");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KategorieFarbe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Kurztext")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VeroeffentlichtAm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewsBeitraege");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.Umfrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndetAm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErstelltVon")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Frage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartetAm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Umfragen");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.UmfrageOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UmfrageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UmfrageId");

                    b.ToTable("UmfrageOptionen");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.UmfrageStimme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbgestimmtAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UmfrageId")
                        .HasColumnType("int");

                    b.Property<int>("UmfrageOptionId")
                        .HasColumnType("int");

                    b.Property<string>("WindowsBenutzername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UmfrageOptionId");

                    b.HasIndex("UmfrageId", "WindowsBenutzername")
                        .IsUnique();

                    b.ToTable("UmfrageStimmen");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.UmfrageOption", b =>
                {
                    b.HasOne("Intranet2.Datenbank.Models.Umfrage", "Umfrage")
                        .WithMany("Optionen")
                        .HasForeignKey("UmfrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Umfrage");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.UmfrageStimme", b =>
                {
                    b.HasOne("Intranet2.Datenbank.Models.Umfrage", "Umfrage")
                        .WithMany("Stimmen")
                        .HasForeignKey("UmfrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intranet2.Datenbank.Models.UmfrageOption", "UmfrageOption")
                        .WithMany("Stimmen")
                        .HasForeignKey("UmfrageOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Umfrage");

                    b.Navigation("UmfrageOption");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.Umfrage", b =>
                {
                    b.Navigation("Optionen");

                    b.Navigation("Stimmen");
                });

            modelBuilder.Entity("Intranet2.Datenbank.Models.UmfrageOption", b =>
                {
                    b.Navigation("Stimmen");
                });
#pragma warning restore 612, 618
        }
    }
}
